import redis
from redisgraph import Graph, Node
import urllib.request
import json
from hydrus.hydraspec import doc_maker
import hydrus
from graphviz import Digraph
from hydra_redis.classes_objects import ClassEndpoints
from hydra_redis.collections_endpoint import CollectionEndpoints

class InitialGraph:
        

    def final_file(self,url):
        """Open the given url and read and load the Json data.
        :param url: given url to access the data from the server.
        :return: data loaded from the server.
        """
        response = urllib.request.urlopen(url)
        return json.loads(response.read().decode('utf-8'))


    def get_apistructure(self,entrypoint_node, api_doc):
        """ It breaks the endpoint into two parts collection and classes"""
        self.collection_endpoints = {}
        self.class_endpoints = {}
        print("split entrypoint into 2 types of endpoints collection and classes")
        for support_property in api_doc.entrypoint.entrypoint.supportedProperty:
            if isinstance(
                    support_property,
                    hydrus.hydraspec.doc_writer.EntryPointClass):
                self.class_endpoints[support_property.name] = support_property.id_

            if isinstance(
                    support_property,
                    hydrus.hydraspec.doc_writer.EntryPointCollection):
                self.collection_endpoints[support_property.name] = support_property.id_

        if len(self.class_endpoints.keys())>0:
            clas = ClassEndpoints(self.redis_graph, self.class_endpoints)
            clas.endpointclasses(entrypoint_node, api_doc, self.url)

        if len(self.collection_endpoints.keys())>0:
            coll = CollectionEndpoints(self.redis_graph, self.class_endpoints)
            coll.endpointCollection(
                self.collection_endpoints,
                entrypoint_node,
                api_doc,
                self.url)


    def get_endpoints(self,api_doc, redis_connection):
        """Create node for entrypoint"""
        print("creating entrypoint node")
        entrypoint_properties = {}
        entrypoint_properties["@id"] = str("vocab:Entrypoint")
        entrypoint_properties["url"] = str(
            api_doc.entrypoint.url) + str(api_doc.entrypoint.api)
        entrypoint_properties["supportedOperation"] = "GET"
        entrypoint_node = Node(
            label="id",
            alias="Entrypoint",
            properties=entrypoint_properties)
        self.redis_graph.add_node(entrypoint_node)
        redis_connection.set("EntryPoint", entrypoint_properties)
        return self.get_apistructure(entrypoint_node, api_doc)


    def main(self,new_url,api_doc,check_commit):
        redis_con = redis.Redis(host='localhost', port=6379)
        self.url = new_url
        self.redis_graph = Graph("apidoc", redis_con)
        print("loading... of graph")
        self.get_endpoints(api_doc, redis_con)
        if check_commit:
            print("commiting")
            self.redis_graph.commit()
            # creating whole the graph in redis
            print("done!!!!")
        # uncomment below 2 lines for getting nodes for whole graph
    #    for node in redis_graph.nodes.values():
    #        print("\n",node.alias)
        # uncomment the below lines for show the graph stored in redis
    #    g = Digraph('redis_graph', filename='hydra_graph.gv')
    #    # using graphviz for visualization of graph stored in redis
    #    for edge in redis_graph.edges:
    #        g.edge(edge.src_node.alias, edge.dest_node.alias)
    #    g.view()
    #    #see the graph generated by graphviz


if __name__ == "__main__":
    url = "http://35.224.198.158:8080/api"
    initial_graph = InitialGraph()
    apidoc = initial_graph.final_file(url + "/vocab")
    api_doc = doc_maker.create_doc(apidoc)
    initial_graph.main(url, api_doc,True)
